apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: prd-teste-repo-2
  namespace: prd-ns-integrador
spec:
  maxReplicas: 
  minReplicas: 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prd-teste-repo-2
  targetCPUUtilizationPercentage: 40
