apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: prd-novo-teste-api
  namespace: prd-bs-poupador
spec:
  maxReplicas: 
  minReplicas: 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prd-novo-teste-api
  targetCPUUtilizationPercentage: 40
