apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dev-api-mota-apresentacao
  namespace: dev-bs-poupador
spec:
  maxReplicas: 
  minReplicas: 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dev-api-mota-apresentacao
  targetCPUUtilizationPercentage: 40
