apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: prd-mais-um-teste
  namespace: prd-
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prd-mais-um-teste
  targetCPUUtilizationPercentage: 40
