apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hml-novo-teste-api
  namespace: hml-bs-poupador
spec:
  maxReplicas: 
  minReplicas: 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hml-novo-teste-api
  targetCPUUtilizationPercentage: 40
