apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dev-api-master-present
  namespace: dev-ns-integrador
spec:
  maxReplicas: 
  minReplicas: 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dev-api-master-present
  targetCPUUtilizationPercentage: 40
