apiVersion: apps/v1
kind: Deployment
metadata:
  name: hml-teste-email-env
  namespace: hml-bs-poupador
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hml-teste-email-env
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hml-teste-email-env
    spec:
      containers:
        - name: hml-teste-email-env
          image: "rodrigomotadevops/hml-teste-email-env:1"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: ENVIRONMENT
              value: hml
            - name: ENDPOINT_BM_BROKER_COLETOR
              value: ${DEV_ENDPOINT_BROKER_COLETOR}
            - name: ENDPOINT_RESOURCE_BM_BROKER_COLETOR
              value: '${DEV_ENDPOINT_RESOURCE_BROKER_COLETOR}'
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: '${OTEL_EXPORTER_OTLP_ENDPOINT}'
            - name: 'OTEL_EXPORTER_OTLP_PROTOCOL'
              value: '${OTEL_EXPORTER_OTLP_PROTOCOL}'
            - name: 'OTEL_RESOURCE_ATTRIBUTES'
              value: '${OTEL_RESOURCE_ATTRIBUTES}=dev'   
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
          resources:
            limits:
              cpu: 300m
              memory: 400Mi
            requests:
              cpu: 150m
              memory: 200Mi
      terminationGracePeriodSeconds: 300
