apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dev-api-gestao-portal
  namespace: dev-ns-integrador
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dev-api-gestao-portal
  targetCPUUtilizationPercentage: 40
