apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gestao-portal
  namespace: dev-ns-integrador
spec:
  ingressClassName: nginx
  rules:
    - host: dev-api-gestao-portal.purecloud.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dev-api-gestao-portal
                port:
                  number: 8080
