apiVersion: v1
kind: Service
metadata:
  name: dev-worker-processa-repo
  namespace: dev-ns-integrador
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: dev-worker-processa-repo
  type: ClusterIP
