apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hml-api-sabado
  namespace: hml-ns-sabado-apresentacao
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hml-api-sabado
  targetCPUUtilizationPercentage: 40
