apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hml-apresentacao-banco-master
  namespace: hml-ns-integrador
spec:
  maxReplicas: 
  minReplicas: 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hml-apresentacao-banco-master
  targetCPUUtilizationPercentage: 40
