apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dev-novo-teste-api
  namespace: dev-bs-poupador
spec:
  maxReplicas: 
  minReplicas: 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dev-novo-teste-api
  targetCPUUtilizationPercentage: 40
