apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: prd-teste-email-env
  namespace: prd-bs-poupador
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prd-teste-email-env
  targetCPUUtilizationPercentage: 40
