apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hml-devopsbr
  namespace: hml-bs-poupador
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hml-devopsbr
  targetCPUUtilizationPercentage: 40
