apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hml-mais-um-teste
  namespace: hml-
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hml-mais-um-teste
  targetCPUUtilizationPercentage: 40
