apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: prd-api-teste-zaza
  namespace: prd-bs-poupador
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prd-api-teste-zaza
  targetCPUUtilizationPercentage: 40
