apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hml-worker-processa-dados
  namespace: hml-ns-integrador
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hml-worker-processa-dados
  targetCPUUtilizationPercentage: 40
